[versions]
kotlin = "2.4.10"
kotlinx-serialization-json = "1.9.0"
jna = "5.19.1"

[libraries]
jna = { group = "net.java.dev.jna", name = "jna", version.ref = "jna" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
